baseURL = "https://ccagentorg.github.io/companies/"
languageCode = "en"
title = "Company Docs"
disableKinds = ["rss", "sitemap", "taxonomy", "term"]
[params]
  author = "Cashless Consumer"
  source_url = "https://github.com/srikanthlogic/companies"
